version: '3.8'

services:
  kali:
    image: kali-arm:latest
    container_name: kali
    platform: linux/arm64
    stdin_open: true
    tty: true
    networks:
      - vulnlab_net

  dvwa:
    image: dvwa-arm:latest
    container_name: dvwa
    platform: linux/arm64
    ports:
      - "8843:80"
    depends_on:
      - mysql
    networks:
      - vulnlab_net
    environment:
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_USER=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_ROOT_PASSWORD=root
    command: >
      sh -c "cp /var/www/html/config/config.inc.php.dist /var/www/html/config/config.inc.php \
      && sed -i 's/127.0.0.1/mysql/' /var/www/html/config/config.inc.php \
      && apache2-foreground"

  mysql:
    image: mariadb:10.5
    container_name: mysql
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
    networks:
      - vulnlab_net

  analyzer:
    image: analyzer-arm:latest
    container_name: analyzer
    platform: linux/arm64
    network_mode: "host"
    volumes:
      - ./logs:/data
    command: ["tcpdump", "-i", "any", "-U", "-w", "/data/capture.pcap"]

networks:
  vulnlab_net:
    driver: bridge
